name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: "master"
      - run: ls
      - run: flutter config --enable-web && flutter pub get && flutter build web --release
      - run: |
          cd example/build/web && git init
          git config --global user.email hongpeifeng@163.com
          git config --global user.name hongpeifeng
          git status
          git remote add origin https://github.com/qq631192328/redux_demo.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f